# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: LicenseRef-.amazon.com.-AmznSL-1.0
# Licensed under the Amazon Software License  http://aws.amazon.com/asl/
version: 0.2

env:
  privileged-mode: true
  git-credential-helper: yes

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt update && DEBIAN_FRONTEND=noninteractive apt install -y git htop jq unzip cmake python3-pip tzdata curl
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip && ./aws/install
      - pip3 install git+https://github.com/aws-greengrass/aws-greengrass-gdk-cli.git@v1.3.0
      - echo "Get Yocto SDK:" $YOCTO_SDK_S3_PATH
      - aws s3 cp $YOCTO_SDK_S3_PATH/$YOCTO_SDK_SCRIPT_NAME ./
      - chmod +x $YOCTO_SDK_SCRIPT_NAME
      - ./$YOCTO_SDK_SCRIPT_NAME -y -d /opt/sdk

    finally:
      - echo Exiting the install phase.
  build:
    commands:
      - echo Entered the build phase...
      - echo $S3_GG_COMPONENT_NAME
      - echo Build started on `date`
      - echo "Source Yocto SDK"
      - . $(find /opt/sdk -maxdepth 1 -name *environment*)
      - echo "Generate a gdk-config.json"
      - sed -e "s#<PLACEHOLDER_AUTHOR>#Biga Demo#g" -e "s#<PLACEHOLDER_BUCKET>#$S3_GG_COMPONENT_NAME#g" -e "s#<PLACEHOLDER_REGION>#$AWS_REGION#g" gdk-config.json.template > gdk-config.json
      - cat gdk-config.json
      - gdk component build
      - gdk component publish
    finally:
      - echo Exiting the build phase, finally.
