{
 "title": "AWS IoT FleetWise Demo - Individual Signal Analysis",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vehicleName",
    "label": "Vehicle Id",
    "query": "SELECT distinct(vehicleName) FROM \"FleetWise\".\"FleetWise\""
   },
   {
    "name": "signalName",
    "label": "Name of signal",
    "query": "SELECT distinct(measure_name) from \"FleetWise\".\"FleetWise\""
   },
   {
    "name": "aggregationInterval",
    "label": "Aggregation interval",
    "query": "100ms, 1s, 5s, 10s, 20s, 30s, 1m, 3m, 5m, 30m, 60m"
   },
   { "name": "signalDataType", "label": "Signal data type", "query": "double,bigint" }
  ]
 },
 "panels": [
  {
   "title": "Value history",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "\"FleetWise\"",
     "measure": "Vehicle.AccelerationX",
     "rawQuery": "SELECT vehicleName, BIN(time, ${aggregationInterval}), avg(measure_value::${signalDataType}) AS \"average(${aggregationInterval})\", max(measure_value::double) AS \"max(${aggregationInterval})\", min(measure_value::double) AS \"minimum(${aggregationInterval})\"\nFROM $__database.$__table \nWHERE measure_name = '${signalName}'  and vehicleName = '${vehicleName}'\nGROUP BY vehicleName,BIN(time, ${aggregationInterval}) \nORDER BY BIN(time, ${aggregationInterval})",
     "table": "\"FleetWise\""
    }
   ]
  },
  {
   "title": "Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "database": "\"FleetWise\"",
     "measure": "Vehicle.AccelerationX",
     "rawQuery": "SELECT vehicleName, BIN(time, ${aggregationInterval}), avg(measure_value::${signalDataType}) AS \"Average in ${aggregationInterval}\"\nFROM $__database.$__table \nWHERE measure_name = '${signalName}'  and vehicleName = '${vehicleName}'\nGROUP BY vehicleName,BIN(time, ${aggregationInterval}) \nORDER BY BIN(time, ${aggregationInterval})",
     "table": "\"FleetWise\""
    }
   ]
  },
  {
   "title": "Histogram over time",
   "type": "histogram",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "database": "\"FleetWise\"",
     "measure": "Vehicle.AccelerationX",
     "rawQuery": "SELECT avg(measure_value::${signalDataType}) AS \"value\"\nFROM $__database.$__table \nWHERE measure_name = '${signalName}'  and vehicleName = '${vehicleName}' and $__timeFilter\nGROUP BY vehicleName,BIN(time, ${aggregationInterval}) \nORDER BY BIN(time, ${aggregationInterval})",
     "table": "\"FleetWise\""
    }
   ]
  },
  {
   "title": "Statistics ",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "database": "\"FleetWise\"",
     "measure": "Vehicle.AccelerationX",
     "rawQuery": "SELECT  avg(measure_value::${signalDataType}) AS \"Average ${aggregationInterval}\", max(measure_value::double) AS \"Maximum\", min(measure_value::double) AS \"Minimum\", stddev(measure_value::double) AS \"Standard Deviation\"\nFROM $__database.$__table \nWHERE measure_name = '${signalName}'  and vehicleName = '${vehicleName}' and measure_value::${signalDataType} > 0 and $__timeFilter\n",
     "table": "\"FleetWise\""
    }
   ]
  },
  {
   "title": "Value history",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "database": "\"FleetWise\"",
     "measure": "Vehicle.AccelerationX",
     "rawQuery": "SELECT vehicleName, BIN(time, ${aggregationInterval}) as \"Time bin\", avg(measure_value::${signalDataType}) AS \"Average ${aggregationInterval}\", max(measure_value::double) AS \"Max\", min(measure_value::double) AS \"Min\", stddev(measure_value::double) AS \"Standard Deviation\"\nFROM $__database.$__table \nWHERE measure_name = '${signalName}'  and vehicleName = '${vehicleName}' and measure_value::${signalDataType} > 0 and $__timeFilter\nGROUP BY vehicleName,BIN(time, ${aggregationInterval}) \nORDER BY BIN(time, ${aggregationInterval})",
     "table": "\"FleetWise\""
    }
   ]
  },
  {
   "title": "Hard Brake Event Images",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \n     a.measure_name,\n    from_unixtime(a.time / 1000e0) as processed_time_UTC,\n    a.measure_value_struct.\"types.sensor_msgs_msg_compressedimage\".data as imagelocation\nFROM \n    \"processed_data\".\"processed_data\" a \nWHERE  $__timeFilter(from_unixtime(a.time / 1000e0)) \nAND a.measure_name='Vehicle.Cameras.Front.Image' \nORDER BY \n    a.time DESC\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Age",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "database": "\"FleetWise\"",
     "measure": "Vehicle.AccelerationX",
     "rawQuery": "SELECT (now()-max(time)) as last_timestamp \nFROM $__database.$__table \nwhere measure_name='Vehicle.OBD.ThrottlePosition'  \n",
     "table": "\"FleetWise\""
    }
   ]
  }
 ]
}