{
 "title": "Embedded-Obersvability-Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Thing",
    "query": "SELECT device FROM \"visibility\".\"visibility\" WHERE time between ago(${timeRange}) and now() ORDER BY time DESC LIMIT 250 "
   },
   {
    "name": "AggregationInterval",
    "label": "Aggregation Interval",
    "query": "100ms, 1s, 5s, 10s, 20s, 30s, 1m, 3m, 5m, 15m, 30m, 45m, 60m"
   },
   { "name": "GGComponent", "label": "GG Component", "query": "CAN_Stats" },
   {
    "name": "timeRange",
    "label": "Time Range",
    "query": "1s,5s,15s,30s,1m,5m,10m,15m,30m,1h,6h,12h,1d"
   },
   {
    "name": "NucleusMetric",
    "query": "SELECT measure_name FROM \"visibility\".\"visibility\" WHERE name='ggTelemetry'"
   }
  ]
 },
 "panels": [
  { "title": "CAN Component Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages Received",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawQuery": "SELECT measure_value::bigint as Message_Received, time FROM \"visibility\".\"visibility\" \nWHERE name='CAN_Stats' \nAND measure_name='MessagesReceivedCount'\nAND time between ago(${timeRange}) and now() ORDER BY time DESC LIMIT 10\n"
    }
   ]
  },
  {
   "title": "Data Load",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "SELECT measure_value::double * 100 as Data_Load FROM \"visibility\".\"visibility\" \nWHERE name='CAN_Stats' \nAND measure_name='CANDataLoad' \nAND time between ago(${timeRange}) and now() ORDER BY time DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "SELECT measure_value::double as Data_Throughput\nFROM \"visibility\".\"visibility\" \nWHERE name='CAN_Stats' \nAND measure_name='CANDataThroughput' \nAND time between ago(${timeRange}) and now() ORDER BY time DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Mailbox Read Success/Error",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawQuery": "SELECT measure_value::bigint as Success, time \nFROM \"visibility\".\"visibility\" WHERE measure_name='MailboxReadSuccessCount' \nAND time between ago(15m) and now() ORDER BY time DESC LIMIT 10"
    },
    {
     "rawQuery": "SELECT measure_value::bigint as Error, time FROM \"visibility\".\"visibility\" WHERE measure_name='MailboxReadErrorCount' AND time between ago(15m) and now() ORDER BY time DESC LIMIT 10"
    }
   ]
  },
  { "title": "GreenGrass Component Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }, "repeat": "GGComponent" },
  {
   "title": "NUCLEUS METRIC: ${NucleusMetric}",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 31 },
   "targets": [
    {
     "database": "\"visibility\"",
     "measure": "AbsTime",
     "rawQuery": "SELECT time, if('${NucleusMetric}' = 'CpuUsage', measure_value::double, measure_value::bigint) AS ${NucleusMetric} \nFROM \"visibility\".\"visibility\" \nWHERE measure_name= '${NucleusMetric}'\nAND time between ago(${timeRange}) and now()",
     "table": "\"visibility\""
    }
   ]
  },
  {
   "title": "IPC time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 31 },
   "targets": [
    {
     "rawQuery": "SELECT time, measure_value::bigint \nFROM \"visibility\".\"visibility\" \nWHERE name= 'GreengrassProcessing' \nAND measure_name='Time' \nAND time between ago(15m) and now() ORDER BY time DESC LIMIT 100"
    }
   ]
  },
  { "title": "End to End Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Device, Greengrass, Cloud interaction latency. Component: ${GGComponent}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawQuery": "SELECT to_milliseconds(component_ts - device_ts) as device_to_component, time FROM \"visibility\".\"visibility\" \nWHERE name='${GGComponent}'\nAND time between ago(${timeRange}) and now() ORDER BY time DESC limit 10000\n\n"
    },
    {
     "rawQuery": "SELECT to_milliseconds((time - 4h) - component_ts) as component_to_cloud, time FROM \"visibility\".\"visibility\" \nWHERE name='${GGComponent}' \nAND time between ago(${timeRange}) and now() ORDER BY time DESC limit 10000\n\n"
    }
   ]
  },
  {
   "title": "Rate of Transmission/Reception Change",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 55 },
   "targets": [
    {
     "rawQuery": "with agg AS (\n  SELECT array_agg(measure_value::bigint)[cardinality(array_agg(measure_value::bigint))] as laste,\n  array_agg(measure_value::bigint)[1] as firste,\n  BIN(time, ${AggregationInterval}) AS ts\n  FROM \"visibility\".\"visibility\" \nWHERE name='CAN_Stats' \nAND measure_name='MessagesReceivedCount'\nAND time between ago(${timeRange}) and now()\nGROUP BY BIN(time, ${AggregationInterval}) \nORDER BY BIN(time, ${AggregationInterval})\n) SELECT ts AS time, IF (${AggregationInterval} = '1s', \n(laste-firste) / (SELECT extract(MINUTE FROM ${AggregationInterval})) as Rate_of_Change_Transmission,\n((laste-firste) / (SELECT extract(SECOND FROM ${AggregationInterval}))) as Rate_of_Change_Transmission) FROM agg\n"
    }
   ]
  }
 ]
}