BBLAYERS =+ "\
  ${METADIR}/external/meta-ros/meta-ros2 \
  ${METADIR}/external/meta-ros/meta-ros-common \
  ${METADIR}/external/meta-ros/meta-ros2-galactic \
  ${METADIR}/external/meta-aws \
  ${METADIR}/meta-aws-biga-demo/meta-aws-biga-demo \
  ${METADIR}/external/meta-openembedded/meta-multimedia \
  "
AGL_META_PYTHON = "${METADIR}/external/meta-openembedded/meta-python"
AGL_META_NETWORKING = "${METADIR}/external/meta-openembedded/meta-networking"
AGL_META_FILESYSTEMS = "${METADIR}/external/meta-openembedded/meta-filesystems"
AGL_META_VIRTUALIZATION = "${METADIR}/external/meta-virtualization"
