# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: LicenseRef-.amazon.com.-AmznSL-1.0
# Licensed under the Amazon Software License  http://aws.amazon.com/asl/
version: 0.2

env:
  privileged-mode: true
  git-credential-helper: yes

phases:
  install:
    commands:
      - echo Entered the install phase...
      - export DEBIAN_FRONTEND=noninteractive
      - apt update && apt install -y git htop jq unzip python3 python3-pip doxygen clang-tidy libgtest-dev curl zlib1g-dev
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip && ./aws/install
      - pip3 install git+https://github.com/aws-greengrass/aws-greengrass-gdk-cli.git@v1.3.0
      - python3 -m pip install catkin-pkg lark-parser numpy
      - git clone -b v1.1.0 --single-branch https://github.com/aws/aws-iot-fleetwise-edge.git
      - chmod +x ./aws-iot-fleetwise-edge/tools/install-deps-native.sh
      - ./aws-iot-fleetwise-edge/tools/install-deps-native.sh --with-greengrassv2-support --with-rich-data-support --with-ros2-support --prefix /usr/local
      - apt install -y ros-galactic-ros-base ros-dev-tools
      - source /opt/ros/galactic/setup.bash
      - mkdir -p ~/ros2_ws/src
      - cd ~/ros2_ws/src
      - git clone https://github.com/astuff/astuff_sensor_msgs.git
      - git clone https://github.com/carla-simulator/ros-carla-msgs.git
      - cd ~/ros2_ws
      - rosdep init
      - rosdep update
      - rosdep install --from-paths src --ignore-src -r -y
      - colcon build --symlink-install
    finally:
      - echo Exiting the install phase.
  build:
    commands:
      - echo Entered the build phase...
      - cd $CODEBUILD_SRC_DIR
      - git clone -b v1.1.0 --single-branch https://github.com/aws/aws-iot-fleetwise-edge.git ~/ros2_ws/src/aws-iot-fleetwise-edge
      - echo $S3_GG_COMPONENT_NAME
      - echo Build started on `date`
      - sed -e "s#<PLACEHOLDER_AUTHOR>#Biga Demo#g" -e "s#<PLACEHOLDER_BUCKET>#$S3_GG_COMPONENT_NAME#g" -e "s#<PLACEHOLDER_REGION>#$AWS_REGION#g" gdk-config.json.template > gdk-config.json
      - gdk component build
      - gdk component publish

    finally:
      - echo Exiting the build phase, finally.