version: '1.0'
networkInterfaces:
- interfaceId: '10'
  type: ros2Interface
  ros2Interface:
    subscribeQueueLength: 100
    executorThreads: 2
    introspectionLibraryCompare: ErrorAndFail
- canInterface:
    interfaceName: vcan0
    protocolName: CAN
    protocolVersion: 2.0A
  interfaceId: '1'
  type: canInterface
- obdInterface:
    interfaceName: vcan0
    requestMessageId: 2015
    obdStandard: J1979
    useExtendedIds: false
    hasTransmissionEcu: true
    pidRequestIntervalSeconds: 0
    dtcRequestIntervalSeconds: 0
  interfaceId: '2'
  type: obdInterface
staticConfig:
  bufferSizes:
    dtcBufferSize: 100
    socketCANBufferSize: 10000
    decodedSignalsBufferSize: 10000
    rawCANFrameBufferSize: 10000
  threadIdleTimes:
    inspectionThreadIdleTimeMs: 50
    socketCANThreadIdleTimeMs: 50
    canDecoderThreadIdleTimeMs: 50
  persistency:
    persistencyPath: "/tmp/fleetwise/"
    persistencyPartitionMaxSize: 524288
    persistencyUploadRetryIntervalMs: 10000
  internalParameters:
    readyToPublishDataBufferSize: 10000
    systemWideLogLevel: Trace
    dataReductionProbabilityDisabled: false
    maximumAwsSdkHeapMemoryBytes: 10000000
    logColor: 'Yes'
  publishToCloudParameters:
    maxPublishMessageCount: 1000
    collectionSchemeManagementCheckinIntervalMs: 5000
  mqttConnection:
    connectionType: iotGreengrassV2
    endpointUrl: a3ppm4soy8x4i5-ats.iot.eu-central-1.amazonaws.com
    clientId: vCar
    collectionSchemeListTopic: "$aws/iotfleetwise/eu-central-1/vehicles/vCar/collection_schemes"
    decoderManifestTopic: "$aws/iotfleetwise/eu-central-1/vehicles/vCar/decoder_manifests"
    canDataTopic: "$aws/iotfleetwise/eu-central-1/vehicles/vCar/signals"
    checkinTopic: "$aws/iotfleetwise/eu-central-1/vehicles/vCar/checkins"
    certificateFilename: ""
    privateKeyFilename: ""
  credentialsProvider:
    endpointUrl: cuwdfxcv55sfy.credentials.iot.eu-central-1.amazonaws.com
    roleAlias: GGTokenExchangeRoleNameAlias-eu-central-1
  s3Upload:
    maxEnvelopeSize: 104857600
    multipartSize: 5242880
    maxConnections: 2
  richDataCollection:
    rawDataBufferSize: 21474836480000