---
RecipeFormatVersion: '2020-01-25'
ComponentName: "demo.iot.automotive.fwe"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription:  A component for FleetWise Edge Agent.
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        demo.iot.automotive.fwe:mqttproxy:1:
          policyDescription: Allows access to publish to all topics.
          operations:
          - aws.greengrass#PublishToIoTCore
          - aws.greengrass#SubscribeToIoTCore
          resources:
          - "*"
    fleetwise:
        version: '1.0'
        networkInterfaces:
        - interfaceId: '10'
          type: ros2Interface
          ros2Interface:
            subscribeQueueLength: 100
            executorThreads: 2
            introspectionLibraryCompare: ErrorAndFail
        staticConfig:
          bufferSizes:
            dtcBufferSize: 100
            decodedSignalsBufferSize: 10000
            rawCANFrameBufferSize: 10000
          threadIdleTimes:
            inspectionThreadIdleTimeMs: 50
            socketCANThreadIdleTimeMs: 50
            canDecoderThreadIdleTimeMs: 50
          persistency:
            persistencyPath: "/tmp/fleetwise/"
            persistencyPartitionMaxSize: 524288
            persistencyUploadRetryIntervalMs: 10000
          internalParameters:
            readyToPublishDataBufferSize: 10000
            systemWideLogLevel: Trace
            dataReductionProbabilityDisabled: false
            maximumAwsSdkHeapMemoryBytes: 10000000
            logColor: 'Yes'
          publishToCloudParameters:
            maxPublishMessageCount: 1000
            collectionSchemeManagementCheckinIntervalMs: 5000
          mqttConnection:
            connectionType: iotGreengrassV2
            endpointUrl: a1ihl3llrend5b-ats.iot.us-west-2.amazonaws.com
            clientId: vin100
            collectionSchemeListTopic: "$aws/iotfleetwise/gamma-us-west-2/vehicles/vin100/collection_schemes"
            decoderManifestTopic: "$aws/iotfleetwise/gamma-us-west-2/vehicles/vin100/decoder_manifests"
            canDataTopic: "$aws/iotfleetwise/gamma-us-west-2/vehicles/vin100/signals"
            checkinTopic: "$aws/iotfleetwise/gamma-us-west-2/vehicles/vin100/checkins"
            certificateFilename: ""
            privateKeyFilename: ""
          credentialsProvider:
            endpointUrl: c3sgnr2p4orfaa.credentials.iot.us-west-2.amazonaws.com
            roleAlias: credentials-provider-role
          s3Upload:
            maxEnvelopeSize: 104857600
            multipartSize: 5242880
            maxConnections: 2
          richDataCollection:
            rawDataBufferSize: 2147483648
Manifests:
- Lifecycle:
    Run:
      SetEnv:
        Config: "{configuration:/fleetwise}"
      RequiresPrivilege: true
      Script: |
        echo $Config > config.json
        . /etc/profile.d/ros/setup.sh
        printenv
        {artifacts:path}/aws-iot-fleetwise-edge ./config.json
  Artifacts:
  - URI: s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/aws-iot-fleetwise-edge
    Permission:
      Execute: OWNER
