---
RecipeFormatVersion: '2020-01-25'
ComponentName: "demo.iot.automotive.ipcfReplacement"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: A component that reads CAN and publish messages to IoT
  Core.
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.ipc.pubsub:
        demo.iot.automotive.ipcfReplacement:pubsub:1:
          policyDescription: Allows access to publish to all topics.
          operations:
          - aws.greengrass#PublishToTopic
          resources:
          - "*"
Manifests:
- Lifecycle:
    Run:
      RequiresPrivilege: true
      script: "{artifacts:path}/ipcf_shared_memory_replacement.py"
  Artifacts:
  - URI: s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/ipcf_shared_memory_replacement.py
    Permission:
      Execute: OWNER
