---
RecipeFormatVersion: '2020-01-25'
ComponentName: "demo.iot.automotive.canAnalyzer"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: A component that publishes CAN json data MQTT messages to IoT
  Core.
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        demo.iot.automotive.canAnalyzer:mqttproxy:1:
          policyDescription: Allows access to publish to all topics.
          operations:
          - aws.greengrass#SubscribeToIoTCore
          - aws.greengrass#PublishToIoTCore
          resources:
          - "*"
Manifests:
- Lifecycle:
    Run:
      RequiresPrivilege: true
      script: python3 -u "{artifacts:path}/can_publisher.py" /dev/ttyLF0
  Artifacts:
  - URI: s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/can_publisher.py
    Permission:
      Execute: OWNER
