version: 0.2
run-as: yoctouser

env:
  shell: bash

phases:
  pre_build:
    run-as: root
    commands:
      - chown -R yoctouser /sstate-cache
      - chown -R yoctouser /downloads
      - chmod 755 /sstate-cache
      - chmod 755 /downloads
  build:
    commands:
    # todo this should be a tag!
      - git clone https://github.com/aws4embeddedlinux/meta-aws-demos -b master-next
      - cd meta-aws-demos
      - git submodule update --init --recursive
      - git clone -b kirkstone https://github.com/DRK-512/meta-ros.git layers/sw/meta-ros
      - ls -al
      - pwd
      - ls layers/sw/meta-ros/
      - . ./init-build-env $TMP_DIR
      - cat $CODEBUILD_SRC_DIR/local.conf >> $TMP_DIR/conf/local.conf
      - . $CODEBUILD_SRC_DIR/meta-aws-demos/init-build-env $TMP_DIR
      - printenv
      - echo build started at `date`
      - export DEMO=biga
      - bitbake aws-biga-image
      - bitbake aws-biga-image -c populate_sdk
      - echo build finished at `date`
  post_build:
    commands:
      # Prune old files in our EFS Mounts, that are not accessed by this or any build within 30 days
      - find /sstate-cache -atime +30 -delete
      - find /downloads -atime +30 -delete

artifacts:
  discard-paths: true
  files:
    - $TMP_DIR/tmp/deploy/images/aws-ec2-arm64/*
    - $TMP_DIR/tmp/deploy/sdk/*
